### ISSUE TITLE
is there anyway to authenticate the request?

### ISSUE THREAD

**Issue by egarim** [jaystack/odata-v4-server#12]
is there anyway to authenticate the request?

**Comment by lazarv** [comment]
Hi @egarim!
Yes you can, just use the OData server as an express.js middleware and you can use passport or any other solution to implement your own authentication logic.
See this blogpost about the topic: [JayStack OData V4 Server – basic authentication](http://jaydata.org/blog/jaystack-odata-v4-server-basic-authentication)
