### ISSUE TITLE
Add plain js example 

### ISSUE THREAD

**Issue by pwasem** [jaystack/odata-v4-server#20]
Would it be possible to add an example using plain javascript with no decorators being used?

Thx

**Comment by lazarv** [comment]
There is an example, here: https://github.com/jaystack/odata-v4-server/blob/master/src/example/es6.js

**Comment by pwasem** [comment]
unfortunately this is not working as expected

**Comment by lazarv** [comment]
@pwasem,
to run it, use:

```
npm run es6
node build/example/es6.js
```

Then you can access the server on ```http://localhost:3000```.
