### ISSUE TITLE
Potential issue with metadata=full and $select

### ISSUE THREAD

**Issue by awright415** [jaystack/odata-v4-server#22]
I haven't been able to find a definitive answer on this, so it might be undefined behavior in the OData spec. But right now, the server returns `<property>@odata.type` metadata about non-string/non-boolean properties that are **excluded** via the `$select` query parameter when a request is made with `odata.metadata=full`.

For example, if you have a Product model with id, description, price, and quantity properties and you issue a request to the server that includes `odata.metadata=full` and `$select=id`. The value section of the response would look something like this, even though price and quantity were not selected: 
```
{
            "@odata.id": "http://www.example.com/odata/Product(1)",
            "@odata.type": "#Product",
            "id@odata.type": "#Int64",
            "id": 11,
            "price@odata.type": "#Decimal",
            "quantity@odata.type": "#Int64",
}
```

Salesforce's built-in OData connector errors out in this situation, stating that it can't deserialize the response. Their implementation seems to rely on the type metadata only being included for the fields listed in `$select`, which seems like a reasonable expectation. But, like I said, I'm not sure what the spec actually calls for. So I don't know who's "right" in this case.

The relevant section of the code base appears to be here: https://github.com/jaystack/odata-v4-server/blob/31e778ff4280ee98f5138e94a537518335eaf3b8/src/lib/processor.ts#L1404

**Comment by lazarv** [comment]
Hi @awright415,
according to the WebAPI OData implementation (using public demo endpoint: http://services.odata.org/V4/TripPinServiceRW) when you use __odata.metadata=full__ in the __Accept__ header and use the __$select__ projection query option, then metadata information should be included only for the selected fields. The referenced commit resolves this issue and latest version (0.2.9) from __npm__ includes this fix.
