### ISSUE TITLE
Perform performance tests

### ISSUE THREAD

**Issue by robesz** [jaystack/odata-v4-server#6]
We might be able to reuse the comparison that was used to evaluate the parser

**Comment by lazarv** [comment]
i7-4500U @ 1.80Ghz 2.39Ghz 16GB RAM 64-bit

[http://localhost:3000/odata/Categories](http://localhost:3000/odata/Categories) (8 category)

odata-v4-inmemory 2000rps
odata-v4-mongodb 1200rps
expressjs+mongodb 1600rps

[http://localhost:3000/odata/Products](http://localhost:3000/odata/Products) (76 product)

odata-v4-inmemory 1200rps
odata-v4-mongodb 600rps
expressjs+mongodb 750rps
